camel-tooling/camel-debug-adapter

.settings/Test camel-dap-server.launch, .settings/camel-debug-adapter.launch, pom.xml, src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java
- from PID, able to retrieve the JMX connection (using sun.tools but not
found a better way)
- allow self attach when launching test so that we can have the Camel
route in the same VM in the tests. Won't be necessary at runtime.
- it requires Camel 3.15
kudos to @javaduke which helped and pointed to helpful code from
IntelliJ extension
https://github.com/javaduke/camel-idea-plugin/blob/main/camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java#L505
=> Attach to Process using provided PID and retrieve Camel BacklogDebugger  MBean

pom.xml
using argLine is overriding the argLine set by Jacoco Maven plugin and
so failing to provide coverage. Using the (cleaner) systemProperties
configuration tag avoids to override the argLine
=> Fix code coverage

README.md, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java
the protocol doesn't have a removeBreakpoint methods, it is calling the
setBreakpoints on the same Source with a different set of breakpoints to
set
=> Support remove of breakpoints

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/main/java/com/github/cameltooling/dap/internal/IdUtils.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelBreakpoint.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelStackFrame.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelThread.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java, src/test/java/com/github/cameltooling/dap/internal/MultipleThreadsTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeAllTest.java
- Showing threads only for stopped message. It would bloats the UI too
much on each running message and surely make it flickering.
- Call Starting/exiting Threads when breakpoint hit, resume all. Threads
id are not reused but this is an arbitrary number anyway. The name is
more important for the end-user perspective, it is the exchange ID.
Cannot use the Exchange ID as thread id because the threadid in Debug
Adapter protocol specification is a number and Exchange ID is a string.
- it is important for Eclipse client to call the thread start and stop,
otherwise, it is not clearing the list of threds even after a new call
on threads() method
=> Use one thread per exchange

pom.xml
note: waiting 3.15 camel release and removal of apache snapshots from repositories to use dependabot, see https://issues.redhat.com/browse/FUSETOOLS2-1448
=> Upgrade slf4j-api to 1.7.33

Contributing.md, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
launch request is not supported by Camel Debug Adapter server, it was
redirecting to the attach because I wasn't aware of the `"request": "attach"` parameter see
https://github.com/eclipse/lsp4e/issues/49#issuecomment-1020190833
thanks to @jonahgraham for pointing it out
=> Remove workaround for launch

pom.xml
it is required for publishing on Sonatype Maven repository
=> FUSETOOLS2-1462 - provide developers info in pom

pom.xml
it is mandatory for publishing on Sonatype Maven repository
=> FUSETOOLS2-1452 - provide source jar

.github/workflows/ci.yaml
given that now it is building on a matrix of jdk (11 and 17)
=> Correct name of JDK setup in github actions

.github/workflows/main.yaml, pom.xml
see https://github.com/camel-tooling/camel-debug-adapter/runs/4981883859?check_suite_focus=true#step:4:131 for a modified branch allowing to see successful signing
- 2 secrets have been provided on GitHub camel-debug-adapter repository:
MAVEN_GPG_PRIVATE_KEY and MAVEN_GPG_PASSPHRASE . They are mine (apupier)
gpg keys and passphrase. The private key must be provided including the
"delimiters" `-----BEGIN PGP PRIVATE KEY BLOCK-----` and `-----END PGP
PRIVATE KEY BLOCK-----`
- the signing is done in verify phase so modified job for it
- the signing requires to be on a branch from the repository as it is
using secrets so cannot be tested on a normal Pull Request. That's the
reason of the profile to sign.
- doing the Sonar and Signing in the same Github Action flow to avoid
rebuilding and …
=> FUSETOOLS2-1458 - Sign jar on Main branch

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelDebuggerScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelEndpointScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelExchangeScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelMessageScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelProcessorScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelThread.java, src/test/java/com/github/cameltooling/dap/internal/ResumeSingleThreadTest.java
It comes with a refactor to have a better scoping of variables. It
really ease reading code as the scope per Exchange becomes important to
be able to deal with as one Exchange is a thread. It will be slower in
terms of performance but it should not have a visible impact unless
there are a lot of breakpoints at the same time, which will anyway won't
be very readable in UI
=> FUSETOOLS2-1433 - resume a single thread

src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java
the error message was that the size was 0 and expecting 5 but when
displaying the error message, the list had 5 elements. So was just a
matter of awaiting correctly.
=> FUSETOOLS2-1485 - avoid test flakiness

src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/NextStepTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeAllTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeSingleThreadTest.java
In the test, the dummy client is not really Thread-safe. Try to wait
that it finishes to collect all datas, before calling a resume/continue.
=> FUSETOOLS2-1493 - avoid test flakiness

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
use a copy of the Set of threads when trying to access the list of
variables
=> FUSETOOLS2-1495 - avoid ConcurrentModificationException

src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/MultipleThreadsTest.java, src/test/java/com/github/cameltooling/dap/internal/NextStepTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeAllTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeSingleThreadTest.java
of breakpoint in test of Camel DAP
now using a marker, so when modifying the file, no more need to update
all breakpoints line.
Nota: it helped also to spot an error in one test where the incorrect
lien was specific as comment and incorrect sourcePath provided in teh
tests (without incidence to runtime)
=> FUSETOOLS2-1510 - Provide a more resilient way to indicate line number

README.md, pom.xml, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugForJavaTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugForYamlTest.java, src/test/resources/basic.yaml
- the basic test covering the most common use case is now launched with
both Java and Yaml DSL
- not provided a yaml version for other tests, there shouldn't be
something specific to it for now. It would be nice in the future but I
think it already gives enough confidence for now having "just" the most
common scenario covered.
=> FUSETOOLS2-1439 - provide basic test for Yaml route

README.md, pom.xml, src/test/java/com/github/cameltooling/dap/internal/BasicDebugForXmlTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugForXmlWithRoutesTest.java, src/test/resources/basic-withroutes.xml, src/test/resources/basic.xml
- working with route and routes in Camel Main mode
- not working with camelContext but sounds a problem at Camel level
which doesn't provide the backlogDebugger in this case or at least at
another place or with another configuration. Created another issue for this use case https://issues.redhat.com/browse/FUSETOOLS2-1516
=> FUSETOOLS2-1438 - provide test for basic flow with xml

README.md, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelStackFrame.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelDebuggerScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelEndpointScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelExchangeScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelProcessorScope.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/CamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/BodyIncludeFilesCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/BodyIncludeStreamsCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/DebugCounterCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/FallbackTimeoutCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/LoggingLevelCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/debugger/MaxCharsForBodyCamelVariable.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
Concentrated on this subset first.
To notice are the materialization of specific XXXCamelVariable in the
debug model which are responsible to the update of their values.
In next iterations, other "scopes" will be handled.
Nota: not found a nice way to report errors for unsupported one and if the value is invalid. Will keep it for another iteration. In VS Code, there is simply a "Internal error" little message displayed when the value cannot be updated. https://issues.redhat.com/browse/FUSETOOLS2-1574
=> FUSETOOLS2-1570 - Allow update of values for "debugger" variables

src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
by waiting that the client used for test has finished its actions before
moving to next step and potentially stopping the Camel Context
=> FUSETOOLS2-1576 - avoid flaky test

src/test/java/com/github/cameltooling/dap/internal/MultipleThreadsTest.java
avoid that client used for test has finished to access data before the
camelcontext is closed
=> FUSETOOLS2-1567 - avoid flaky test MultipleThreadsTest

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java
Now, when a breakpoint is set before starting the debugger, the
breakpoint is correctly used. The initializedEvent was sent at the wrong
time before, the debugger was not ready to accept the setBreakpoint
requests as the JMX connection was not ready.
=> FUSETOOLS2-1599 - support already set breakpoint

.gitignore, pom.xml, src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java, src/test/java/com/github/cameltooling/dap/internal/ConditionalBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/MultipleThreadsTest.java, src/test/java/com/github/cameltooling/dap/internal/NextStepTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeAllTest.java, src/test/java/com/github/cameltooling/dap/internal/ResumeSingleThreadTest.java, src/test/java/com/github/cameltooling/dap/internal/SuspendTest.java, src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
fixes #106 
Thanks to https://issues.apache.org/jira/browse/CAMEL-18217, it is now possible to suspend the message processing by setting an environment. This feature can be leveraged to avoid having to explicitly add a `sleep` in the code in order to ensure that all the breakpoints have been added.
* Add the support of configuration done to be able to automatically attach the debugger once ready
* Upgrade the version of Camel to have access to the changes for https://issues.apache.org/jira/browse/CAMEL-18217
* Add `junit-pioneer` as test dependency to be able to set the system property within the context of a unit test  
* Rewrite the tests to close the context after the server to prevent warnings of type `java.io.IOException: Failed to get a RMI stub: javax.naming.CommunicationException …
=> Ref #106 - Automatically attach the debugger once ready

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
In the class that has been modified within the context of #106, there are several warnings raised by IntelliJ that could be fixed.
* Use `final` keyword on fields that are not modified which prevents visibility issues
* Avoid setting the size to the array when copying a collection into an array
=> Ref #106 - Fix warnings

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelScope.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelStackFrame.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelThread.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelDebuggerScope.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/exchange/ExchangePropertiesVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageBodyCamelVariable.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageHeadersVariable.java
Some parts of the code are not really thread safe which could lead to un-predictable behaviors, race conditions issues, ConcurrentModificationException... 
Even if the changes of this PR don't make the code fully thread safe as some operations are not atomic but at least it addresses the biggest issues which sounds like a good trade-off for the purpose of this code. Indeed making the code fully thread safe would require to rewrite some parts of the code which is not expected for now. 
* Use `final` keyword on fields that are not modified which prevents visibility issues
* Use thread-safe collections
* Use `volatile` keyword on fields read and written by concurrent threads to prevent visibility and ordering issues
* Use `AtomicInteger` as a thread safe counter
* Use the copy-on-write …
=> Improve the thread-safety of the code

src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java
fixes #114
The variable `UID` in the `MESSAGE` section proposed by the debugger is misleading for the end-user, as it could be interpreted as the `UID` of the Camel message while it is actually the `UID` of the backlog tracer event message which is something very internal to the Debugger and IMHO should not be exposed to the end-user.
* Removes the variable `UID` from the collection of variables to expose
* Fixes the unit tests accordingly
=> Ref #114 - Remove the debugger variable UID

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java, src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java, src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
Fix for https://issues.redhat.com/browse/FUSETOOLS2-1669
* Converts all code of the methods of `CamelDebugAdapterServer` to `Supplier`s or `Runnable`s to call them asynchronously
* Calls `Supplier`s and `Runnable`s using internal utility methods to ensure that the context classloader used is correct otherwise we potentially end up with `java.lang.ClassNotFoundException`
* Fixes the unit tests expecting the calls to be synchronous
* Fixes the visibility issue in `DummyCamelDebugClient`
=> FUSETOOLS2-1669 - Use async code in Debug Adapter Server codebase

src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
throwing a runtime exception in test
reported by Sonar
https://sonarcloud.io/project/issues?issues=AYIRsV6PI60DufTrpFR0&open=AYIRsV6PI60DufTrpFR0&id=camel-tooling_camel-debug-adapter
=> Refactor the code of the lambda to have only one invocation possibly

src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelExchangeScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java
Unfortunately, I'm unable to reproduce the issue in a test. I guess it is due to the way the route is launched but not found the trick
EDIT: I think it is more probably because the client implementation has changed and that the request to all variables became lazy. In oru tests, the "Dummy client" is still not lazy which explains why I do not reproduce, i will need to improve the "DummyClient" implementation in our test suite
=> FUSETOOLS2-1819 - Fix regression when updating value

src/test/java/com/github/cameltooling/dap/internal/BaseTest.java
to avoid potential ConcurrentModificationException
=> FUSETOOLS2-1858 - copy list before asserting on it

.github/dependabot.yml
=> Use a GitHub group to assign Dependabot reviewer - fix name using

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/test/java/com/github/cameltooling/dap/internal/StepInTest.java, src/test/java/com/github/cameltooling/dap/internal/StepOutTest.java
to follow specification: `If the request cannot step into a target, stepIn behaves like the next request.`
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepIn
=> FUSETOOLS2-2142 - redirect stepIn and stepOut to nextStep

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelExchangeScope.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java, src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java
it would throw this kind of exception otherwise: `Caused by: java.lang.NoSuchMethodException:
org.apache.camel.management.mbean.ManagedBacklogDebugger.dumpTracedMessagesAsXml(java.lang.String)`
=> Fix to keep minimal backward compatibility with Camel 4.1-

.github/workflows/ci.yaml
avoid 2 jobs from the matrix uploading with same name
=> Fix upload of artifact log at end of job build

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java, src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageExchangeVariablesVariable.java, src/main/java/com/github/cameltooling/dap/internal/types/ExchangeVariable.java, src/main/java/com/github/cameltooling/dap/internal/types/Message.java, src/main/java/com/github/cameltooling/dap/internal/types/UnmarshallerEventMessage.java, src/test/java/com/github/cameltooling/dap/internal/BaseTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugForJavaTest.java, src/test/java/com/github/cameltooling/dap/internal/types/UnmarshallerEventMessageTest.java, src/test/resources/basic-withroutes.xml, src/test/resources/basic.xml, src/test/resources/basic.yaml
Camel Variables
- https://camel.apache.org/manual/variables.html
- https://camel.apache.org/blog/2024/02/camel44-whatsnew/#variables
- https://raymondmeester.medium.com/camel-variables-new-ways-to-manipulate-data-pipelines-2bf3d31cb26c
-----
This is how the Event Message looks like
```xml
<backlogTracerEventMessage>
<uid>1</uid>
<first>false</first>
<last>false</last>
<rest>false</rest>
<template>false</template>
<timestamp>2024-03-14T15:32:03.349+0100</timestamp>
<elapsed>928</elapsed>
<threadName>Camel (camel-1) thread #6 - timer://foo</threadName>
<done>false</done>
<failed>false</failed>
<location>myapp.java:12</location>
<routeId>route1</routeId>
<toNode>log1</toNode>
<exchangeId>6A28393E31D32D8-0000000000000000</exchangeId>
<message exchangeId="6A28393E31D32D8-0000000000000000" …
```
=> FUSETOOLS2-2299: Display variables values during debugging for Exchange scope

.settings/Test camel-dap-server.launch, README.md, src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java, src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelExchangeThread.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelRouteDefinitionThread.java, src/main/java/com/github/cameltooling/dap/internal/model/CamelStackFrame.java, src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java, src/test/java/com/github/cameltooling/dap/internal/CamelSuspendModeTest.java, src/test/java/com/github/cameltooling/dap/internal/ConditionalBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java, src/test/java/com/github/cameltooling/dap/internal/MultipleThreadsTest.java, src/test/java/com/github/cameltooling/dap/internal/NextStepTest.java, src/test/java/com/github/cameltooling/dap/internal/PauseRouteDefinitionTest.java, src/test/java/com/github/cameltooling/dap/internal/RemoveBreakpointTest.java, src/test/java/com/github/cameltooling/dap/internal/StepInTest.java, src/test/java/com/github/cameltooling/dap/internal/StepOutTest.java
/!\ in VS Code, when there is a single thread (which means a single
route running for us), the thread is not displayed!!!
/!\ in VS Code, when there is a single thread (which means a single
route running for us), the thread is not displayed!!!
Next iterations:
- provide more information on the route displayed in the variables, when
on pause, it will avoid having empty views when pausing and there is a
single route https://issues.redhat.com/browse/FUSETOOLS2-2416
- provide route instances suspended when the route definition is
suspended - requires https://issues.apache.org/jira/browse/CAMEL-20908
=> FUSETOOLS2-2407- Support Pause for all routes and route by route

.github/workflows/main.yaml
current error:
```
Error:  Failed to execute goal
org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy
(injected-nexus-deploy) on project camel-dap-server: Failed to deploy
artifacts: Could not transfer artifact
com.github.camel-tooling:camel-dap-server:jar:javadoc:1.2.0-20240628.075713-4
from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots):
authentication failed for
https://oss.sonatype.org/content/repositories/snapshots/com/github/camel-tooling/camel-dap-server/1.2.0-SNAPSHOT/camel-dap-server-1.2.0-20240628.075713-4-javadoc.jar,
status: 401 Content access is protected by token -> [Help 1]
```
secrets in configuration of github repository has been updated
=> Fix deploy by using encrypted username

pom.xml, src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java
by simply adding Jolokia 2 as a dependency
Writing a test is complicated, might be easier to provide an end to end test at VS code level. reported https://issues.redhat.com/browse/FUSETOOLS2-2424
=> FUSETOOLS2-1428 - Activate JMX over http

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
it is useful during some investigation but this is not an error
=> Change log level from ERROR to INFO for number of threads
