src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java

- support a single Route and a single context for now
- test will need to be improved to be robust
- only Java DSL tested

Allow to set breakpoints

---

.github/workflows/ci.yaml
.github/workflows/sonar.yaml

i allows to simplify cache declaration

use setup-java action v2

---

.settings/camel-debug-adapter.launch
README.md
pom.xml
src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/main/java/com/github/cameltooling/dap/internal/types/EventMessage.java
src/main/java/com/github/cameltooling/dap/internal/types/ExchangeProperty.java
src/main/java/com/github/cameltooling/dap/internal/types/Header.java
src/main/java/com/github/cameltooling/dap/internal/types/Message.java
src/main/java/com/github/cameltooling/dap/internal/types/UnmarshallerEventMessage.java
src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java
src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java
src/test/java/com/github/cameltooling/dap/internal/StackAndVarOnStopEvent.java
src/test/java/com/github/cameltooling/dap/internal/types/UnmarshallerEventMessageTest.java

Provide first iteration support of basic flow: set breakpoint, have it suspended, provide a bunch of variables (not all yet) and resume

---

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java
src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java

Provide more variables

---

.github/workflows/ci.yaml

Do it only on Ubuntu to save resources.

Add job to test with JDK 17

---

README.md

Update information about clients

---

Contributing.md

Provide initial information how to develop the Camel Debug Adapter

---

src/main/java/com/github/cameltooling/dap/internal/model/CamelStackFrame.java
src/main/java/com/github/cameltooling/dap/internal/model/CamelThread.java

detected by Sonar
https://sonarcloud.io/project/issues?id=camel-tooling_camel-debug-adapter&issues=AX6Ln_qBKcvyCvHUXEBM&open=AX6Ln_qBKcvyCvHUXEBM

Remove unused attributes

---

src/main/java/com/github/cameltooling/dap/internal/model/CamelBreakpoint.java

spotted by Sonar
https://sonarcloud.io/project/issues?id=camel-tooling_camel-debug-adapter&issues=AX6Ln_naKcvyCvHUXEBK&open=AX6Ln_naKcvyCvHUXEBK

provide equals and hashcode

---

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java

including structured variables which have children and does not display
value directly
it is a requirement due to VS Code implementation limitation
https://github.com/microsoft/vscode/issues/141544

FUSETOOLS2-1434 - provide non-null value for all variables

---

.github/workflows/ci.yaml

requires https://github.com/camel-tooling/camel-debug-adapter/pull/29

1466 store log on ci

---

.github/workflows/main.yaml
pom.xml

see https://github.com/camel-tooling/camel-debug-adapter/runs/4982110542?check_suite_focus=true#step:4:499 for a succesful publish on slightly modified branch to be able to test it
requires https://github.com/camel-tooling/camel-debug-adapter/pull/32

Fusetools2 1464 publish

---

.github/workflows/ci.yaml

FUSETOOLS2-1491 - store log file on failure too

---

pom.xml

FUSETOOLS2-1494 - display stacktraces when test is in error

---

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/main/java/com/github/cameltooling/dap/internal/telemetry/TelemetryEvent.java
src/test/java/com/github/cameltooling/dap/internal/BaseTest.java
src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java

called
combined with VS Code, we can have this kind of report:

FUSETOOLS2-1489 - Send telemetry message when attach debug session

---

README.md
src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java
src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageBodyCamelVariable.java
src/test/java/com/github/cameltooling/dap/internal/BasicDebugFlowTest.java
src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java

FUSETOOLS2-1571 - allow update of Message Body value

---

README.md
src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelExchangeScope.java
src/main/java/com/github/cameltooling/dap/internal/model/variables/exchange/ExchangePropertiesVariable.java
src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java

FUSETOOLS2-1573 - Support update of Exchange property values when string

---

README.md
src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/test/java/com/github/cameltooling/dap/internal/BaseTest.java
src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java

waiting fro Camel 3.16 release before merging. Will need to remove the snapshot depednency and repository.
Camel 3.16.0 is planned for end of next week.

FUSETOOLS2-1427 - support JMX connection

---

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/DummyCamelDebugClient.java
src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java

FUSETOOLS2-1574 - Provide information on error output when updating

---

pom.xml

Prepare release 0.1.0

---

Contributing.md

Provide information to release

---

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/test/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServerTest.java

FUSETOOLS2-1598 - provide error message to guide user when debugger

---

pom.xml

Prepare release 0.2.0

---

pom.xml

Prepare next development iteration 0.3.0-SNAPSHOT

---

Contributing.md

Simplify contributing guide to debug Language Server

---

README.md
src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/BaseTest.java
src/test/java/com/github/cameltooling/dap/internal/ConditionalBreakpointTest.java

FUSETOOLS2-1436 - support conditional breakpoint with simple language

---

README.md

Add information in readme about the suspend  on start capabilities with

---

Contributing.md

Improve release guide

---

README.md

opportunity to update VS Code information and to add vim tutorial

provide specific section for clients

---

src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java

Improve warning message by providing a space between path and line

---

pom.xml
src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java
src/main/java/com/github/cameltooling/dap/internal/CamelDebugAdapterServer.java
src/test/java/com/github/cameltooling/dap/internal/UnverifiedBreakpointTest.java

FUSETOOLS2-1670 - improve message on non verified breakpoints

---

.github/workflows/ci.yaml

remove Java 18 as it is not an LTS, just test with latest stable release

Use Java 19 in CI

---

src/main/java/com/github/cameltooling/dap/internal/BacklogDebuggerConnectionManager.java

it will avoid having the thread continue to run and hitting potential
NPE or closed connection to the MBean
it will help to stabilize test suite. From a functional level of end-user, the only impact should be less stacktrace in logs

FUSETOOLS2-1846 - Interrupt thread checking suspended node when terminating

---

pom.xml

it is attached to the artifact with a specific classifier
```
[INFO] Installing /home/apupier/git/camel-debug-adapter/target/bom.xml to /home/apupier/.m2/repository/com/github/camel-tooling/camel-dap-server/0.10.0-SNAPSHOT/camel-dap-server-0.10.0-SNAPSHOT-cyclonedx.xml
[INFO] Installing /home/apupier/git/camel-debug-adapter/target/bom.json to /home/apupier/.m2/repository/com/github/camel-tooling/camel-dap-server/0.10.0-SNAPSHOT/camel-dap-server-0.10.0-SNAPSHOT-cyclonedx.json
```

FUSETOOLS2-2198 - Generate sbom

---

.github/workflows/ci.yaml
pom.xml

* removing Java 20 which is not an LTS

Test with JDK 21

---

src/main/java/com/github/cameltooling/dap/internal/model/scopes/CamelMessageScope.java
src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageExchangePropertiesVariable.java
src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageExchangeVariablesVariable.java
src/main/java/com/github/cameltooling/dap/internal/model/variables/message/MessageHeadersVariable.java
src/main/java/com/github/cameltooling/dap/internal/types/ExchangeVariable.java
src/main/java/com/github/cameltooling/dap/internal/types/Message.java
src/test/java/com/github/cameltooling/dap/internal/UpdateDebuggerVariableValueTest.java

FUSETOOLS2-2321: Update exchange variable values during debugging

---

.github/workflows/main.yaml
pom.xml

* https://central.sonatype.org/news/20250326_ossrh_sunset/#questions
* https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
I updated the tokens in github config

FUSETOOLS2-2584 - migrate from OSSRH to Central
